"""make admin-form fields nullable

Revision ID: 26f004251c05
Revises: add_notification_channel
Create Date: 2026-07-01 22:59:16.920742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f004251c05'
down_revision = 'add_notification_channel'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('certificates', 'issuing_body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('certificates', 'issue_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('certificates', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'hospital_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'logo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hero_slides', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hero_slides', 'heading',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_openings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_openings', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_openings', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_openings', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'service_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('service_products', 'service_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('service_products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'short_desc',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('team_members', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('team_members', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('testimonials', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('testimonials', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('testimonials', 'hospital_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('testimonials', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testimonials', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('testimonials', 'hospital_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('testimonials', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('testimonials', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('team_members', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('team_members', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'short_desc',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('services', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('service_products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('service_products', 'service_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'service_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_openings', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_openings', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_openings', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_openings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hero_slides', 'heading',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hero_slides', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'logo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'hospital_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('certificates', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('certificates', 'issue_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('certificates', 'issuing_body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('certificates', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
