"""add homepage stats fields to site settings

Revision ID: 6d5bd7799fa9
Revises: 26f004251c05
Create Date: 2026-07-06 22:24:18.687342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5bd7799fa9'
down_revision = '26f004251c05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('years_experience', sa.Integer(), server_default='12', nullable=False))
    op.add_column('site_settings', sa.Column('hospitals_served', sa.Integer(), server_default='185', nullable=False))
    op.add_column('site_settings', sa.Column('cities_covered', sa.Integer(), server_default='45', nullable=False))
    op.add_column('site_settings', sa.Column('core_products', sa.Integer(), server_default='8', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'core_products')
    op.drop_column('site_settings', 'cities_covered')
    op.drop_column('site_settings', 'hospitals_served')
    op.drop_column('site_settings', 'years_experience')
    # ### end Alembic commands ###
